### ISSUE TITLE
Session cookies don't automatically set secure flag on HTTPS connections

### ISSUE THREAD

**Issue by ddelbondio** [agavi/agavi#1541]
The code in AgaviSessionStorage checks if session_get_cookie_params()['secure'] is null, which it never is, so the automatic setting of the secure flag never works.
Refs #981

**Comment by dzuelke** [comment]
This is/was intentional. By default, Agavi respects what's set in `session.cookie_secure`; you can explicitly set an "Agavi level" setting by setting `session_cookie_secure` to `true` or `false`, or have the auto-detect that uses `AgaviWebRequest::isHttps()` (which IMO is relatively useless) by leaving that parameter empty (== `null`).

**Comment by dzuelke** [comment]
So... I'm not sure if or what this even fixes, but it seems... unnecessary?

**Comment by ddelbondio** [comment]
Since the fix is nice in theory, but also would cause a major bc break without adding anything substantial i reverted it in 4a60ea10585b01443aad4ff22cfc289e199ab5de
